# POST https://backend-rntl.onrender.com/api/login HTTP/1.1
# content-type: application/json

# {
#     "email": "Admin",
#     "password": "admin"
# }


POST http://localhost:7878/api/login HTTP/1.1
content-type: application/json

{
    "email": "Admin",
    "password": "admin"
}